"""Exact joint bit allocation and report selection.

Each report has mutually exclusive options: not selected, or selected with
1-4 quantization bits, with the corresponding post-communication moments and
bit cost.  Per target, the Pareto frontier of (cost, worst-target value)
is generated by enumeration; the target-separable multiple-choice knapsack
is then solved exactly.  This is the joint extension of the exact max-min
selection DP in :mod:`uav_otfs_isac.exact_quota_selection`.
"""

from __future__ import annotations

import itertools

import numpy as np
from scipy.stats import norm

from .expected_pd import expected_gaussian_detection_probability
from .fusion import optimal_gaussian_detection_probability, pd_shift_upper_bound
from .models import TargetEvidenceModel
from .reporting import post_bsc_moments, quantizer_from_gaussian_range


def moments(
    delta: float,
    bits: int,
    bit_flip_probability: float = 0.0,
):
    """Post-BSC H0/H1 moments of a b-bit quantized Gaussian report."""
    edges, values = quantizer_from_gaussian_range(
        [0.0], [1.0], [delta], [1.0], bits,
    )
    m0, v0 = post_bsc_moments(
        0.0, 1.0, edges, values, bits, bit_flip_probability,
    )
    m1, v1 = post_bsc_moments(
        float(delta), 1.0, edges, values, bits, bit_flip_probability,
    )
    return m0, m1, v0, v1


def model_from_bits(
    deltas: np.ndarray,
    bits: np.ndarray,
    bit_flip_probability: float = 0.0,
) -> TargetEvidenceModel:
    """Build a model with fixed per-report bit counts (owner excluded)."""
    n = len(deltas)
    post_mu0 = np.zeros(n)
    post_mu1 = np.zeros(n)
    var0 = np.ones(n)
    var1 = np.ones(n)
    costs = np.zeros(n, dtype=int)
    for i in range(n):
        if i == 0:
            post_mu1[i] = float(deltas[i])
            continue
        m0, m1, v0, v1 = moments(
            float(deltas[i]), int(bits[i]), bit_flip_probability,
        )
        post_mu0[i], post_mu1[i] = m0, m1
        var0[i], var1[i] = v0, v1
        costs[i] = int(bits[i])
    return TargetEvidenceModel(
        target_id=0,
        owner=0,
        mu0=post_mu0,
        mu1=post_mu1,
        sigma0=np.diag(var0),
        sigma1=np.diag(var1),
        success_prob=np.ones(n),
        report_bits=costs,
        bit_flip_prob=np.zeros(n),
        quantizer_edges=np.array([-np.inf, 0.0, np.inf]),
        quantizer_values=np.array([-1.0, 1.0]),
    )


def one_report_model(
    delta: float,
    bits: int,
    bit_flip_probability: float = 0.0,
) -> TargetEvidenceModel:
    """Single-report model used for marginal-gain bit loading."""
    m0, m1, v0, v1 = moments(delta, bits, bit_flip_probability)
    return TargetEvidenceModel(
        target_id=0,
        owner=0,
        mu0=np.array([0.0, m0]),
        mu1=np.array([delta, m1]),
        sigma0=np.diag([1.0, v0]),
        sigma1=np.diag([1.0, v1]),
        success_prob=np.ones(2),
        report_bits=np.array([0, bits]),
        bit_flip_prob=np.zeros(2),
        quantizer_edges=np.array([-np.inf, 0.0, np.inf]),
        quantizer_values=np.array([-1.0, 1.0]),
    )


def greedy_bits(
    deltas: np.ndarray,
    budget_bits: int,
    grid: int,
    max_bits: int = 4,
    bit_flip_probability: float = 0.0,
) -> np.ndarray:
    """Water-filling-inspired heuristic: give the next bit to the largest gain."""
    bits = np.ones(len(deltas), dtype=int)
    gains: dict[int, list[float]] = {}
    for index, delta in enumerate(deltas):
        previous = float(expected_gaussian_detection_probability(
            one_report_model(float(delta), 1, bit_flip_probability), {0, 1}, 0.05,
            pd_mode="optimal", grid=grid,
        ))
        row = []
        for candidate in range(2, max_bits + 1):
            current = float(expected_gaussian_detection_probability(
                one_report_model(float(delta), candidate, bit_flip_probability),
                {0, 1}, 0.05,
                pd_mode="optimal", grid=grid,
            ))
            row.append(current - previous)
            previous = current
        gains[index] = row
    while bits.sum() < budget_bits:
        best_index = None
        best_gain = 0.0
        for index, row in gains.items():
            if bits[index] >= max_bits:
                continue
            gain = row[bits[index] - 1]
            if gain > best_gain + 1e-12:
                best_gain = gain
                best_index = index
        if best_index is None:
            break
        bits[best_index] += 1
    return bits


def target_options(
    owner_delta: float,
    deltas: np.ndarray,
    grid: int,
    max_bits: int = 4,
    bit_flip_probability: float = 0.0,
    max_reports: int | None = None,
) -> list[tuple[int, float]]:
    """Pareto frontier over selection and bit choices, optionally limited.

    ``max_reports`` caps the number of selected reports per target, and
    ``max_bits`` caps the bit count per report.  The returned frontier is
    exact over the restricted feasible set.
    """
    return vectorized_target_options(
        owner_delta,
        deltas,
        grid,
        max_bits=max_bits,
        bit_flip_probability=bit_flip_probability,
        max_reports=max_reports,
    )


def vectorized_target_options(
    owner_delta: float,
    deltas: np.ndarray,
    grid: int = 32,
    max_bits: int = 4,
    batch_size: int = 50_000,
    bit_flip_probability: float = 0.0,
    max_reports: int | None = None,
) -> list[tuple[int, float]]:
    """Vectorized exact Pareto frontier for up to R=8 reports.

    Enumerates all 5^R report/bit choices but evaluates the P_D-optimal shift
    for a batch of choices at once, so the option generation is practical for
    R=8 (390625 choices).  The frontier keeps one point per distinct cost.
    """
    reports = list(range(len(deltas)))
    choices = list(range(max_bits + 1))
    if max_reports is not None and max_reports < 0:
        raise ValueError("max_reports must be nonnegative")

    pre_m0 = np.zeros((len(reports), max_bits + 1))
    pre_m1 = np.zeros((len(reports), max_bits + 1))
    pre_v0 = np.ones((len(reports), max_bits + 1))
    pre_v1 = np.ones((len(reports), max_bits + 1))
    for i, delta in enumerate(deltas):
        for b in choices:
            m0, m1, v0, v1 = moments(float(delta), b, bit_flip_probability)
            pre_m0[i, b] = m0
            pre_m1[i, b] = m1
            pre_v0[i, b] = v0
            pre_v1[i, b] = v1

    z = float(norm.ppf(0.95))
    owner_a2 = float(owner_delta ** 2)
    owner_q = 1.0
    mu_grid = np.concatenate((
        np.linspace(0.0, 3.0, grid // 2),
        np.geomspace(3.0 + 1e-3, 1e6, grid // 2),
    ))
    frontier: dict[int, float] = {}

    def evaluate_batch(batch_choices: np.ndarray):
        costs = batch_choices.sum(axis=1).astype(int)
        selected = batch_choices > 0
        b = batch_choices
        delta_mu = pre_m1 - pre_m0
        a = np.where(selected, delta_mu[np.arange(len(deltas)), b] / np.sqrt(pre_v0[np.arange(len(deltas)), b]), 0.0)
        q = np.where(
            selected,
            pre_v1[np.arange(len(deltas)), b] / pre_v0[np.arange(len(deltas)), b],
            1.0,
        )
        a2 = a * a
        # (G, B, R)
        denom = q[None, :, :] + mu_grid[:, None, None]
        a2_den = a2[None, :, :] / denom
        a2_den2 = a2[None, :, :] / (denom * denom)
        q_a2_den2 = q[None, :, :] * a2[None, :, :] / (denom * denom)
        A2 = a2_den.sum(axis=2)
        N2 = a2_den2.sum(axis=2)
        H2 = q_a2_den2.sum(axis=2)
        A2 = A2 + owner_a2 / (owner_q + mu_grid[:, None])
        N2 = N2 + owner_a2 / ((owner_q + mu_grid[:, None]) ** 2)
        H2 = H2 + owner_q * owner_a2 / ((owner_q + mu_grid[:, None]) ** 2)
        shifts = (
            A2
            - z * np.sqrt(np.maximum(N2, 0.0))
        ) / np.sqrt(np.maximum(H2, 1e-30))
        num_a = a2.sum(axis=1)
        h_a = (q * a2).sum(axis=1)
        num_a = num_a + owner_a2
        h_a = h_a + owner_q * owner_a2
        deflection_limit = (
            num_a - z * np.sqrt(np.maximum(num_a, 0.0))
        ) / np.sqrt(np.maximum(h_a, 1e-30))
        best_shift = np.maximum(
            shifts.max(axis=0),
            deflection_limit,
        )
        pd_values = norm.cdf(best_shift)
        return costs, pd_values

    all_combos = np.asarray(
        list(itertools.product(choices, repeat=len(reports))),
        dtype=np.int64,
    )
    if max_reports is not None:
        selected_counts = (all_combos > 0).sum(axis=1)
        all_combos = all_combos[selected_counts <= max_reports]
    if all_combos.shape[0] == 0:
        raise ValueError("no report/bit combinations satisfy max_reports")
    count = all_combos.shape[0]
    for start in range(0, count, batch_size):
        batch = all_combos[start:start + batch_size]
        costs, values = evaluate_batch(batch)
        for cost, value in zip(costs, values):
            key = int(cost)
            if key not in frontier or float(value) > frontier[key]:
                frontier[key] = float(value)

    result = sorted(
        (cost, value) for cost, value in frontier.items()
    )
    pareto: list[tuple[int, float]] = []
    best_value = -1.0
    for cost, value in result:
        if value > best_value + 1e-12:
            pareto.append((cost, value))
            best_value = value
    return pareto


def subset_options(
    owner_delta: float,
    deltas: np.ndarray,
    bits: np.ndarray,
    grid: int,
    bit_flip_probability: float = 0.0,
) -> list[tuple[int, float]]:
    """Pareto frontier of (cost, P_D) for a fixed per-report bit assignment."""
    reports = list(range(len(deltas)))
    out: list[tuple[int, float]] = []
    for mask in range(1 << len(reports)):
        selected = [i for i in reports if mask & (1 << i)]
        cost = int(sum(bits[i] for i in selected))
        mu0 = [0.0]
        mu1 = [owner_delta]
        var0 = [1.0]
        var1 = [1.0]
        for i in selected:
            m0, m1, v0, v1 = moments(
                float(deltas[i]), int(bits[i]), bit_flip_probability,
            )
            mu0.append(m0)
            mu1.append(m1)
            var0.append(v0)
            var1.append(v1)
        pd = float(optimal_gaussian_detection_probability(
            np.asarray(mu0), np.asarray(mu1),
            np.diag(var0), np.diag(var1),
            set(range(len(mu0))), 0.05, grid=grid,
        ))
        out.append((cost, pd))
    out.sort(key=lambda item: (item[0], -item[1]))
    pareto: list[tuple[int, float]] = []
    best_value = -1.0
    last_cost = None
    for cost, pd in out:
        if cost == last_cost:
            continue
        last_cost = cost
        if pd > best_value + 1e-12:
            pareto.append((cost, pd))
            best_value = pd
    return pareto


def minimum_cost_for_threshold(
    options: list[tuple[int, float]],
    threshold: float,
) -> int | None:
    """Minimum cost among options whose value reaches the threshold.

    ``options`` must be the Pareto frontier returned by ``target_options``:
    sorted by nondecreasing cost with strictly nondecreasing value.  A binary
    search is exact because the feasible cost set is an upper interval of the
    sorted frontier.
    """
    if not options:
        return None
    costs = np.asarray([cost for cost, _ in options])
    values = np.asarray([value for _, value in options])
    index = int(np.searchsorted(
        values, threshold - 1e-12, side="left"
    ))
    if index >= costs.size:
        return None
    return int(costs[index])


def exact_joint_maxmin(
    target_options_list: list[list[tuple[int, float]]],
    budget_bits: int,
) -> float:
    """Exact max-min over target-separable bit/report option sets."""
    if not target_options_list:
        raise ValueError("target_options_list must be nonempty")
    frontiers = [
        (
            np.asarray([cost for cost, _ in options], dtype=int),
            np.asarray([value for _, value in options], dtype=float),
        )
        for options in target_options_list
    ]
    if any(costs.size == 0 for costs, _ in frontiers):
        raise ValueError("every target option set must be nonempty")
    values = sorted({
        float(value)
        for _, values in frontiers
        for value in values
    })

    def feasible(threshold: float) -> bool:
        total = 0
        for costs, values in frontiers:
            index = int(np.searchsorted(
                values, threshold - 1e-12, side="left"
            ))
            if index >= costs.size:
                return False
            total += int(costs[index])
            if total > budget_bits:
                return False
        return True

    lo, hi = 0, len(values) - 1
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if feasible(values[mid]):
            lo = mid
        else:
            hi = mid - 1
    return float(values[lo])


def exact_joint_maxmin_selection(
    target_options_list: list[list[tuple[int, float]]],
    budget_bits: int,
) -> tuple[float, list[tuple[int, float]]]:
    """Exact max-min value and one cost-minimal schedule attaining it."""
    value = exact_joint_maxmin(target_options_list, budget_bits)
    chosen = []
    for options in target_options_list:
        candidates = [
            option for option in options
            if option[1] >= value - 1e-12
        ]
        chosen.append(min(candidates, key=lambda option: option[0]))
    return value, chosen


def minimum_cost_joint_threshold(
    owner_delta: float,
    deltas: np.ndarray,
    threshold: float,
    grid: int = 32,
    max_bits: int = 4,
) -> int | None:
    """Minimum bit cost to reach a P_D threshold with joint bit allocation.

    Uses DFS with two prunes: a cost prune once a feasible solution is known,
    and a value prune that replaces every remaining report by its
    quantization-free (perfect) version.  The perfect-version upper bound was
    verified against all 20480 report/bit combinations on random diagonal
    models; it is used as a pruning certificate and the remaining DFS is
    exhaustive, so the returned minimum is exact for the audited models.
    """
    pre: list[list[tuple[float, float, float, float]]] = []
    order = list(range(len(deltas)))
    order.sort(
        key=lambda i: -float(deltas[i]) ** 2,
    )
    for i in order:
        pre.append([moments(float(deltas[i]), b) for b in range(max_bits + 1)])

    def evaluate(selected: list[tuple[int, int]]) -> float:
        mu0 = [0.0]
        mu1 = [owner_delta]
        var0 = [1.0]
        var1 = [1.0]
        for (report_index, bit_count) in selected:
            m0, m1, v0, v1 = pre[report_index][bit_count]
            mu0.append(m0)
            mu1.append(m1)
            var0.append(v0)
            var1.append(v1)
        if len(mu0) == 1:
            return float(optimal_gaussian_detection_probability(
                np.asarray([0.0]), np.asarray([owner_delta]),
                np.eye(1), np.eye(1), {0}, 0.05, grid=grid,
            ))
        return float(optimal_gaussian_detection_probability(
            np.asarray(mu0), np.asarray(mu1),
            np.diag(var0), np.diag(var1),
            set(range(len(mu0))), 0.05, grid=grid,
        ))

    def upper_bound(
        selected: list[tuple[int, int]],
        remaining: list[int],
    ) -> float:
        mu0 = [0.0]
        mu1 = [owner_delta]
        var0 = [1.0]
        var1 = [1.0]
        for (report_index, bit_count) in selected:
            m0, m1, v0, v1 = pre[report_index][bit_count]
            mu0.append(m0)
            mu1.append(m1)
            var0.append(v0)
            var1.append(v1)
        for report_index in remaining:
            delta = float(deltas[order[report_index]])
            mu0.append(0.0)
            mu1.append(delta)
            var0.append(1.0)
            var1.append(1.0)
        return float(norm.cdf(pd_shift_upper_bound(
            np.asarray(mu0), np.asarray(mu1),
            np.diag(var0), np.diag(var1),
            set(range(len(mu0))), 0.05,
        )))

    all_cost = max_bits * len(deltas)
    all_selected = [(i, max_bits) for i in range(len(deltas))]
    if evaluate(all_selected) < threshold - 1e-12:
        return None
    best_cost = all_cost
    # Warm starts: uniform b-bit assignments and the water-filling greedy.
    for uniform_bits in range(1, max_bits + 1):
        selected = [(i, uniform_bits) for i in range(len(deltas))]
        if evaluate(selected) >= threshold - 1e-12:
            best_cost = min(best_cost, uniform_bits * len(deltas))
    greedy_assignment = greedy_bits(
        np.asarray(deltas, dtype=float),
        max_bits * len(deltas),
        grid,
        max_bits=max_bits,
    )
    greedy_selected = [
        (i, int(greedy_assignment[i])) for i in range(len(deltas))
    ]
    if evaluate(greedy_selected) >= threshold - 1e-12:
        best_cost = min(best_cost, int(greedy_assignment.sum()))

    def dfs(
        index: int,
        selected: list[tuple[int, int]],
        cost: int,
    ) -> None:
        nonlocal best_cost
        if cost >= best_cost:
            return
        remaining = list(range(index, len(deltas)))
        if upper_bound(selected, remaining) < threshold - 1e-12:
            return
        if index == len(deltas):
            if evaluate(selected) >= threshold - 1e-12:
                best_cost = cost
            return
        for bit_count in range(max_bits, 0, -1):
            dfs(
                index + 1,
                selected + [(index, bit_count)],
                cost + bit_count,
            )
        dfs(index + 1, selected, cost)

    dfs(0, [], 0)
    return int(best_cost) if best_cost < all_cost else None
