"""Exact joint bit allocation and report selection.

Each report has mutually exclusive options: not selected, or selected with
1-4 quantization bits, with the corresponding post-communication moments and
bit cost.  Per target, the Pareto frontier of (cost, worst-target value)
is generated by enumeration; the target-separable multiple-choice knapsack
is then solved exactly.  This is the joint extension of the exact max-min
selection DP in :mod:`uav_otfs_isac.exact_quota_selection`.
"""

from __future__ import annotations

import itertools

import numpy as np

from .expected_pd import expected_gaussian_detection_probability
from .fusion import optimal_gaussian_detection_probability
from .models import TargetEvidenceModel
from .reporting import post_bsc_moments, quantizer_from_gaussian_range


def moments(delta: float, bits: int):
    """Post-BSC H0/H1 moments of a b-bit quantized Gaussian report."""
    edges, values = quantizer_from_gaussian_range(
        [0.0], [1.0], [delta], [1.0], bits,
    )
    m0, v0 = post_bsc_moments(0.0, 1.0, edges, values, bits, 0.0)
    m1, v1 = post_bsc_moments(float(delta), 1.0, edges, values, bits, 0.0)
    return m0, m1, v0, v1


def model_from_bits(deltas: np.ndarray, bits: np.ndarray) -> TargetEvidenceModel:
    """Build a model with fixed per-report bit counts (owner excluded)."""
    n = len(deltas)
    post_mu0 = np.zeros(n)
    post_mu1 = np.zeros(n)
    var0 = np.ones(n)
    var1 = np.ones(n)
    costs = np.zeros(n, dtype=int)
    for i in range(n):
        if i == 0:
            post_mu1[i] = float(deltas[i])
            continue
        m0, m1, v0, v1 = moments(float(deltas[i]), int(bits[i]))
        post_mu0[i], post_mu1[i] = m0, m1
        var0[i], var1[i] = v0, v1
        costs[i] = int(bits[i])
    return TargetEvidenceModel(
        target_id=0,
        owner=0,
        mu0=post_mu0,
        mu1=post_mu1,
        sigma0=np.diag(var0),
        sigma1=np.diag(var1),
        success_prob=np.ones(n),
        report_bits=costs,
        bit_flip_prob=np.zeros(n),
        quantizer_edges=np.array([-np.inf, 0.0, np.inf]),
        quantizer_values=np.array([-1.0, 1.0]),
    )


def one_report_model(delta: float, bits: int) -> TargetEvidenceModel:
    """Single-report model used for marginal-gain bit loading."""
    m0, m1, v0, v1 = moments(delta, bits)
    return TargetEvidenceModel(
        target_id=0,
        owner=0,
        mu0=np.array([0.0, m0]),
        mu1=np.array([delta, m1]),
        sigma0=np.diag([1.0, v0]),
        sigma1=np.diag([1.0, v1]),
        success_prob=np.ones(2),
        report_bits=np.array([0, bits]),
        bit_flip_prob=np.zeros(2),
        quantizer_edges=np.array([-np.inf, 0.0, np.inf]),
        quantizer_values=np.array([-1.0, 1.0]),
    )


def greedy_bits(
    deltas: np.ndarray,
    budget_bits: int,
    grid: int,
    max_bits: int = 4,
) -> np.ndarray:
    """Water-filling-inspired heuristic: give the next bit to the largest gain."""
    bits = np.ones(len(deltas), dtype=int)
    gains: dict[int, list[float]] = {}
    for index, delta in enumerate(deltas):
        previous = float(expected_gaussian_detection_probability(
            one_report_model(float(delta), 1), {0, 1}, 0.05,
            pd_mode="optimal", grid=grid,
        ))
        row = []
        for candidate in range(2, max_bits + 1):
            current = float(expected_gaussian_detection_probability(
                one_report_model(float(delta), candidate), {0, 1}, 0.05,
                pd_mode="optimal", grid=grid,
            ))
            row.append(current - previous)
            previous = current
        gains[index] = row
    while bits.sum() < budget_bits:
        best_index = None
        best_gain = 0.0
        for index, row in gains.items():
            if bits[index] >= max_bits:
                continue
            gain = row[bits[index] - 1]
            if gain > best_gain + 1e-12:
                best_gain = gain
                best_index = index
        if best_index is None:
            break
        bits[best_index] += 1
    return bits


def target_options(
    owner_delta: float,
    deltas: np.ndarray,
    grid: int,
    max_bits: int = 4,
) -> list[tuple[int, float]]:
    """Pareto frontier of (cost, P_D) over selection and 1-4 bit choices."""
    options = [[(0, 0.0, 0.0, 1.0, 1.0)] for _ in deltas]
    for index, delta in enumerate(deltas):
        for bits in range(1, max_bits + 1):
            options[index].append((bits, *moments(float(delta), bits)))
    out: list[tuple[int, float]] = []
    for combo in itertools.product(*options):
        cost = sum(item[0] for item in combo)
        mu0 = [0.0]
        mu1 = [owner_delta]
        var0 = [1.0]
        var1 = [1.0]
        for (bits, m0, m1, v0, v1) in combo:
            if bits > 0:
                mu0.append(m0)
                mu1.append(m1)
                var0.append(v0)
                var1.append(v1)
        pd = float(optimal_gaussian_detection_probability(
            np.asarray(mu0), np.asarray(mu1),
            np.diag(var0), np.diag(var1),
            set(range(len(mu0))), 0.05, grid=grid,
        ))
        out.append((cost, pd))
    out.sort(key=lambda item: (item[0], -item[1]))
    pareto: list[tuple[int, float]] = []
    best_value = -1.0
    last_cost = None
    for cost, pd in out:
        if cost == last_cost:
            continue
        last_cost = cost
        if pd > best_value + 1e-12:
            pareto.append((cost, pd))
            best_value = pd
    return pareto


def subset_options(
    owner_delta: float,
    deltas: np.ndarray,
    bits: np.ndarray,
    grid: int,
) -> list[tuple[int, float]]:
    """Pareto frontier of (cost, P_D) for a fixed per-report bit assignment."""
    reports = list(range(len(deltas)))
    out: list[tuple[int, float]] = []
    for mask in range(1 << len(reports)):
        selected = [i for i in reports if mask & (1 << i)]
        cost = int(sum(bits[i] for i in selected))
        mu0 = [0.0]
        mu1 = [owner_delta]
        var0 = [1.0]
        var1 = [1.0]
        for i in selected:
            m0, m1, v0, v1 = moments(float(deltas[i]), int(bits[i]))
            mu0.append(m0)
            mu1.append(m1)
            var0.append(v0)
            var1.append(v1)
        pd = float(optimal_gaussian_detection_probability(
            np.asarray(mu0), np.asarray(mu1),
            np.diag(var0), np.diag(var1),
            set(range(len(mu0))), 0.05, grid=grid,
        ))
        out.append((cost, pd))
    out.sort(key=lambda item: (item[0], -item[1]))
    pareto: list[tuple[int, float]] = []
    best_value = -1.0
    last_cost = None
    for cost, pd in out:
        if cost == last_cost:
            continue
        last_cost = cost
        if pd > best_value + 1e-12:
            pareto.append((cost, pd))
            best_value = pd
    return pareto


def exact_joint_maxmin(
    target_options_list: list[list[tuple[int, float]]],
    budget_bits: int,
) -> float:
    """Exact max-min over target-separable bit/report option sets."""
    values = sorted({value for options in target_options_list for _, value in options})

    def feasible(threshold: float) -> bool:
        total = 0
        for options in target_options_list:
            best = None
            for cost, value in options:
                if value >= threshold - 1e-12 and (best is None or cost < best):
                    best = cost
            if best is None:
                return False
            total += best
            if total > budget_bits:
                return False
        return True

    lo, hi = 0, len(values) - 1
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if feasible(values[mid]):
            lo = mid
        else:
            hi = mid - 1
    return float(values[lo])
